### ISSUE TITLE
열공하네 ㅋㅋ

### ISSUE THREAD

**Issue by kobevino** [marvelopers/Foundation_FE#1]
내 깃허브는 어케 안거지?

**Comment by marvelopers** [comment]
> 내 깃허브는 어케 안거지?

우와 이런 기능 있는지 처음알았어여!
전에 물어봤었는디 깃허브!! 엘제이한테!! ㅋㅋㅋㅋㅋ

**Comment by vinomuse** [comment]
> > 내 깃허브는 어케 안거지?
> 
> 우와 이런 기능 있는지 처음알았어여!
> 전에 물어봤었는디 깃허브!! 엘제이한테!! ㅋㅋㅋㅋㅋ

**Comment by kobevino** [comment]
> > 내 깃허브는 어케 안거지?
> 
> 우와 이런 기능 있는지 처음알았어여!
> 전에 물어봤었는디 깃허브!! 엘제이한테!! ㅋㅋㅋㅋㅋ

그랬나? 근데 내가 아이디를 바꿔서. 그전부터 팔로우가 되어 있었나보네.

**Comment by marvelopers** [comment]
이거 닫아도 쓸 수 있는건가??
어어 맞아여! 전에 준 아이디 없다고 나와서 뭘 다시치니까 같은 프사가 나왔던거 같은디, 기억이 잘 안나네ㅋㅋㅋㅋ
